#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#

module "webapp" {
  source = "./module-webapp"

  customer = var.customer
  env      = var.env
  extra_tags = {
    demo                 = true
    monitoring_discovery = false
  }
  git_app_url      = "https://github.com/Yog9/SnapShot.git"
  keypair_public   = var.keypair_public
  project          = var.project
  vm_disk_size     = 20
  vm_instance_type = "t3a.small"
}

