version: "2"
use_cases:
- name: default
  sections:
  - name: Config
    groups:
    - name: terraform
      technologies:
      - terraform
      vars:
      - widget: text_area
        required: true
        default: vpc-2ba25a4d
        type: string
        key: aws_subnet_pub_subnet_vpc_id
        name: aws_subnet_pub_subnet_vpc_id
